version: 2
updates:
  # poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  # poetry LTS
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/v3.23"
