FAKE_LIBRARIES = {'value': [{'id': 'abcd', 'displayName': 'Documents'}]}

FAKE_SHEET = {
    '@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#workbookRange',
    '@odata.type': '#microsoft.graph.workbookRange',
    '@odata.id': '/users("a6c30179-14c9-4b1d-8769-1a50bd4fd2ed")/drive/root/workbook/worksheets(%27%7BE6B4A4BA-FBD2-4FBA-B7D6-6F4CF520564A%7D%27)/usedRange(valuesOnly=true)',
    'address': 'DataType!A1:H3',
    'addressLocal': 'DataType!A1:H3',
    'columnCount': 8,
    'cellCount': 24,
    'columnHidden': False,
    'rowHidden': False,
    'numberFormat': [
        [
            'General',
            'General',
            'General',
            'General',
            'General',
            '[$-x-sysdate]dddd, mmmm dd, yyyy',
            '[$-en-US]d/m/yy h:mm AM/PM;@',
            'General',
        ],
        [
            'General',
            'General',
            'General',
            "_-[$$-en-US]* #,##0.00_ ;_-[$$-en-US]* -#,##0.00 ;_-[$$-en-US]* '-'??_ ;_-@_ ",
            'm/d/yyyy',
            '[$-x-sysdate]dddd, mmmm dd, yyyy',
            '[$-en-US]d/m/yy h:mm AM/PM;@',
            'General',
        ],
        [
            'General',
            'General',
            'General',
            "_-[$$-en-US]* #,##0.00_ ;_-[$$-en-US]* -#,##0.00 ;_-[$$-en-US]* '-'??_ ;_-@_ ",
            'm/d/yyyy',
            '[$-x-sysdate]dddd, mmmm dd, yyyy',
            '[$-en-US]d/m/yy h:mm AM/PM;@',
            'm/d/yyyy',
        ],
    ],
    'columnIndex': 0,
    'text': [
        [
            'col_text',
            'col_int',
            'col_float',
            'col_money',
            'col_date',
            'col_datetime',
            'col_datetime_bis',
            'col_mixed_type',
        ],
        [
            'foo',
            '1',
            '1,1',
            ' $1,00 ',
            '01/01/2021',
            'samedi 2 janvier 2021',
            '2/1/21 12:02 PM',
            'toto',
        ],
        [
            'bar',
            '2',
            '2,2',
            ' $2,00 ',
            '02/01/2021',
            'dimanche 3 janvier 2021',
            '23/4/21 9:07 PM',
            '01/01/2021',
        ],
    ],
    'formulas': [
        [
            'col_text',
            'col_int',
            'col_float',
            'col_money',
            'col_date',
            'col_datetime',
            'col_datetime_bis',
            'col_mixed_type',
        ],
        ['foo', 1, 1.1, 1, 44197, 44198, 44198.5017476852, 'toto'],
        ['bar', 2, 2.2, 2, 44198, 44199, 44309.8798958333, 44197],
    ],
    'formulasLocal': [
        [
            'col_text',
            'col_int',
            'col_float',
            'col_money',
            'col_date',
            'col_datetime',
            'col_datetime_bis',
            'col_mixed_type',
        ],
        ['foo', 1, 1.1, 1, 44197, 44198, 44198.5017476852, 'toto'],
        ['bar', 2, 2.2, 2, 44198, 44199, 44309.8798958333, 44197],
    ],
    'formulasR1C1': [
        [
            'col_text',
            'col_int',
            'col_float',
            'col_money',
            'col_date',
            'col_datetime',
            'col_datetime_bis',
            'col_mixed_type',
        ],
        ['foo', 1, 1.1, 1, 44197, 44198, 44198.5017476852, 'toto'],
        ['bar', 2, 2.2, 2, 44198, 44199, 44309.8798958333, 44197],
    ],
    'hidden': False,
    'rowCount': 3,
    'rowIndex': 0,
    'valueTypes': [
        ['String', 'String', 'String', 'String', 'String', 'String', 'String', 'String'],
        ['String', 'Double', 'Double', 'Double', 'Double', 'Double', 'Double', 'String'],
        ['String', 'Double', 'Double', 'Double', 'Double', 'Double', 'Double', 'Double'],
    ],
    'values': [
        [
            'col_text',
            'col_int',
            'col_float',
            'col_money',
            'col_date',
            'col_datetime',
            'col_datetime_bis',
            'col_mixed_type',
        ],
        ['foo', 1, 1.1, 1, 44197, 44198, 44198.5017476852, 'toto'],
        ['bar', 2, 2.2, 2, 44198, 44199, 44309.8798958333, 44197],
    ],
}
